### ISSUE TITLE
New board contains empty blocks when width is ≥ 44

### ISSUE THREAD

**Issue by al-joshwilliams** [jodawill/same#2]
<img width="842" alt="screen shot 2015-10-16 at 10 13 43 am" src="https://cloud.githubusercontent.com/assets/14997939/10543916/9a96bdcc-73ee-11e5-938c-f68b20a7b21f.png">

**Comment by jodawill** [comment]
In src/graphics.c, draw_display() was printing a bunch of spaces to clear part of the screen. These spaces were wrapped to the beginning of the screen. Fix in progress.

**Comment by jodawill** [comment]
Fixed as of 4438d3.
